@usuarioId = 1
@listaId = 1

### GET listas usuarios
GET {{url}}/usuarios/{{usuarioId}}/listas


### GET lista specifica por usuario
GET {{url}}/usuarios/{{usuarioId}}/listas/{{listaId}}


### POST Criar lista por usuario
POST {{url}}/usuarios/{{usuarioId}}/listas
Content-Type: application/json

{
  "nome": "Coisas pra comprar pro show da Lady Gaga"
}

### PUT Atualizar lista do usuario
 PUT {{url}}/usuarios/{{usuarioId}}/listas/{{listaId}}
Content-Type: application/json

{
  "nome": "Sexy Shop da Lady Gaga",
  "descricao": "Lady gaga fracassada"
}