### GET usuarios
GET http://localhost:8080/usuarios


### GET usuarios
GET http://localhost:8080/usuarios/1


### POST Criar usuarios
POST http://localhost:8080/usuarios
Content-Type: application/json

{
    "nome": "thomas",
    "email": "thomborges2@gmail.com",
    "senha":"12345"
}

### PUT Atualizar usuarios
PUT http://localhost:8080/usuarios/1
Content-Type: application/json

{
  "nome": "thomas",
  "email": "thomborges21cm@gmail.com",
  "senha":"12345"
}

### DELETE Deletar usuarios
DELETE http://localhost:8080/usuarios/1
Content-Type: application/json