@usuarioId = 1
@listaId = 1
@tarefaId = 1

### GET tarefa da lista
GET {{url}}/usuarios/{{usuarioId}}/listas/{{listaId}}/tarefas

### GET tarefa da lista com status
GET {{url}}/usuarios/{{usuarioId}}/listas/{{listaId}}/tarefas?status=TODO,DONE


### GET tarefa specifica para lista
GET {{url}}/usuarios/{{usuarioId}}/listas/{{listaId}}/tarefas/{{tarefaId}}


### POST Criar tarefa por usuario
POST {{url}}/usuarios/{{usuarioId}}/listas/{{listaId}}/tarefas
Content-Type: application/json

{
  "nome": "DILDO de 128cm"
}

### PUT Atualizar tarefa do lista
 PUT {{url}}/usuarios/{{usuarioId}}/listas/{{listaId}}/tarefas/{{tarefaId}}
Content-Type: application/json

{
  "nome": "Sexy Shop da Lady Gaga",
  "descricao": "Lady gaga fracassada",
}

### Concluir tarefa
PUT {{url}}/usuarios/{{usuarioId}}/listas/{{listaId}}/tarefas/{{tarefaId}}/concluir

### Desfazer tarefa
PUT {{url}}/usuarios/{{usuarioId}}/listas/{{listaId}}/tarefas/{{tarefaId}}/desfazer
