### GET usuarios
GET {{url}}/usuarios


### GET usuarios
GET {{url}}/usuarios/1


### POST Criar usuarios
POST {{url}}/usuarios
Content-Type: application/json

{
    "nome": "thomas",
    "email": "thomborges2@gmail.com",
    "senha":"12345"
}

### PUT Atualizar usuarios
PUT {{url}}/usuarios/1
Content-Type: application/json

{
  "nome": "thomas",
  "email": "thomborges21cm@gmail.com",
  "senha":"12345"
}

### DELETE Deletar usuarios
DELETE {{url}}/usuarios/1
Content-Type: application/json